name: Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install server dependencies
        working-directory: rwa-base
        run: yarn install --frozen-lockfile

      - name: Install test dependencies
        working-directory: api-ui-tests
        run: yarn install --frozen-lockfile

      - name: Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: api-ui-tests
          start: 'yarn --cwd ../rwa-base dev'
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          install: false
          spec: 'cypress/tests/ui/e2e/**/*.cy.js'

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Results
          path: |
            api-ui-tests/cypress/screenshots
            api-ui-tests/cypress/videos
            api-ui-tests/cypress/results
          if-no-files-found: ignore
